#!/usr/bin/env node
// Rem Design System — token generator.
// Single source: ../tokens/tokens.json  ->  generated Swift + CSS.
//
//   node generate-tokens.mjs            # write generated files
//   node generate-tokens.mjs --check    # exit 1 if generated files are stale (CI drift guard)
//
// Branches on each token's $kind:
//   value      -> literal on every platform
//   reference  -> Swift keeps the adaptive system-color reference (#if os), web uses approximate hex
//
// The generated Swift is TOKEN VALUES ONLY. Hand-written helpers (Color(hex:), ShimmerModifier,
// the macOS Layout frame hints) stay in a non-generated companion file — see SPEC "Cutover plan".

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, "..", "tokens", "tokens.json");
const OUT_SWIFT = join(HERE, "..", "Sources", "RemDesignSystem", "DesignTokens.generated.swift");
const OUT_CSS = join(HERE, "..", "tokens", "generated", "tokens.generated.css");
const OUT_KT = join(HERE, "..", "tokens", "generated", "RemTokens.kt");

const T = JSON.parse(readFileSync(SRC, "utf8"));
const HEADER_SWIFT = `// GENERATED by tools/generate-tokens.mjs from tokens.json.\n// DO NOT EDIT BY HAND. Run the generator and commit. Helpers live in the companion file.\n`;
const HEADER_CSS = `/* GENERATED by tools/generate-tokens.mjs from tokens.json. DO NOT EDIT BY HAND. */`;

// ---- helpers ----------------------------------------------------------------
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const hexToRGB = (hex) => {
  const h = hex.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
};

// ---- SWIFT ------------------------------------------------------------------
function swiftColorLiteral(hex) {
  const [r, g, b] = hexToRGB(hex);
  return `SwiftUI.Color(red: ${r}/255, green: ${g}/255, blue: ${b}/255)`;
}
function swiftAdaptiveClosure(light, dark) {
  const [lr, lg, lb] = hexToRGB(light);
  const [dr, dg, db] = hexToRGB(dark);
  return `{
        #if os(iOS)
        return SwiftUI.Color(UIColor { $0.userInterfaceStyle == .dark
            ? UIColor(red: ${dr}/255, green: ${dg}/255, blue: ${db}/255, alpha: 1)
            : UIColor(red: ${lr}/255, green: ${lg}/255, blue: ${lb}/255, alpha: 1) })
        #else
        return SwiftUI.Color(nsColor: NSColor(name: nil) { $0.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
            ? NSColor(red: ${dr}/255, green: ${dg}/255, blue: ${db}/255, alpha: 1)
            : NSColor(red: ${lr}/255, green: ${lg}/255, blue: ${lb}/255, alpha: 1) })
        #endif
    }()`;
}
function swiftColorDecl(name, tok) {
  if (tok.$kind === "reference" && tok.swift?.ios) {
    return `        #if os(iOS)\n        public static let ${name} = ${tok.swift.ios}\n        #else\n        public static let ${name} = ${tok.swift.macos}\n        #endif`;
  }
  if (tok.$kind === "reference" && typeof tok.swift === "string") {
    return `        public static let ${name} = ${tok.swift}`;
  }
  if (tok.$kind === "value" && tok.value) {
    return `        public static let ${name} = ${swiftColorLiteral(tok.value)}`;
  }
  if (tok.$kind === "value" && tok.light && tok.dark) {
    return `        public static let ${name}: SwiftUI.Color = ${swiftAdaptiveClosure(tok.light, tok.dark)}`;
  }
  return `        // (unmapped) ${name}`;
}
const swiftTextStyle = (r) => {
  let f = `Font.system(.${r.textStyle}, design: .${r.family === "mono" ? "monospaced" : "default"})`;
  if (r.weight === 700) f += `.weight(.bold)`;
  return f;
};

function buildSwift() {
  const c = T.color;
  const colorLines = [];
  colorLines.push(swiftColorDecl("backgroundPrimary", c.background.primary));
  colorLines.push(swiftColorDecl("backgroundSecondary", c.background.secondary));
  colorLines.push(swiftColorDecl("backgroundTertiary", c.background.tertiary));
  colorLines.push(swiftColorDecl("labelPrimary", c.label.primary));
  colorLines.push(swiftColorDecl("labelSecondary", c.label.secondary));
  colorLines.push(swiftColorDecl("labelTertiary", c.label.tertiary));
  colorLines.push(swiftColorDecl("labelOnColor", c.label.onColor));
  colorLines.push(swiftColorDecl("separator", c.separator));
  colorLines.push(swiftColorDecl("fillTertiary", c.fill.tertiary));
  colorLines.push(swiftColorDecl("buttonBackground", c.buttonBackground));
  colorLines.push(swiftColorDecl("pillBackground", c.pillBackground));
  for (const [k, v] of Object.entries(c.system)) {
    if (k.startsWith("$")) continue;
    colorLines.push(swiftColorDecl(`system${k[0].toUpperCase()}${k.slice(1)}`, { $kind: "reference", swift: v.swift }));
  }
  colorLines.push(swiftColorDecl("brandBlue", c.brand.blue));
  colorLines.push(swiftColorDecl("brandBlueOnFill", c.brand.blueOnFill));

  const spacing = Object.entries(T.spacing).filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `        public static let ${k}: CGFloat = ${v}`).join("\n");
  const radius = Object.entries(T.radius).filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `        public static let ${k}: CGFloat = ${v}`).join("\n");

  const roles = T.typography.roles;
  const typo = Object.entries(roles).map(([k, r]) => `        public static let ${k} = ${swiftTextStyle(r)}`).join("\n");
  const aliases = Object.entries(T.typography.roleAliases).filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `        public static let ${k} = ${v}`).join("\n");
  const tracking = `        public static let title3Tracking: CGFloat = ${roles.title3.letterSpacing}`;

  return `${HEADER_SWIFT}import SwiftUI
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

public enum DesignTokens {
    public enum Color {
${colorLines.join("\n")}
    }

    public enum Spacing {
${spacing}
    }

    public enum CornerRadius {
${radius}
    }

    public enum Typography {
${typo}
${tracking}
${aliases}
    }

    public enum Opacity {
        public static let deemphasized: Double = ${T.opacity.deemphasized.value}
    }
}
`;
}

// ---- CSS --------------------------------------------------------------------
const webVal = (tok) => (typeof tok.web === "object" ? tok.web : { light: tok.value });
function cssColorVars(light) {
  const c = T.color, out = [];
  const push = (name, tok) => {
    const w = webVal(tok);
    out.push(`  --rem-color-${name}: ${light ? w.light : (w.dark ?? w.light)};`);
  };
  push("background-primary", c.background.primary);
  push("background-secondary", c.background.secondary);
  push("background-tertiary", c.background.tertiary);
  push("label-primary", c.label.primary);
  push("label-secondary", c.label.secondary);
  push("label-tertiary", c.label.tertiary);
  push("label-on-color", c.label.onColor);
  push("separator", c.separator);
  push("fill-tertiary", c.fill.tertiary);
  push("button-background", c.buttonBackground);
  push("pill-background", c.pillBackground);
  for (const [k, v] of Object.entries(c.system)) { if (!k.startsWith("$")) push(`system-${k}`, v); }
  out.push(`  --rem-color-brand-blue: ${c.brand.blue.value};`);
  out.push(`  --rem-color-brand-blue-on-fill: ${light ? c.brand.blueOnFill.light : c.brand.blueOnFill.dark};`);
  return out.join("\n");
}
function buildCSS() {
  const spacing = Object.entries(T.spacing).filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `  --rem-space-${k}: ${v}px;`).join("\n");
  const radius = Object.entries(T.radius).filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `  --rem-radius-${k}: ${v}px;`).join("\n");
  const roles = T.typography.roles;
  const type = Object.entries(roles).map(([k, r]) =>
    `  --rem-font-${kebab(k)}-size: ${r.size}px;\n  --rem-font-${kebab(k)}-weight: ${r.weight};`).join("\n");
  return `${HEADER_CSS}
:root {
  --rem-font-family: ${T.typography.fontFamily.value};
  --rem-font-family-mono: ${T.typography.fontFamilyMono.value};
${type}
  --rem-letter-spacing-title3: ${roles.title3.letterSpacing}px;
${spacing}
${radius}
  --rem-opacity-deemphasized: ${T.opacity.deemphasized.value};
${cssColorVars(true)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${cssColorVars(false)}
  }
}
:root[data-theme="dark"] {
${cssColorVars(false)}
}
`;
}

// ---- KOTLIN (Jetpack Compose) ----------------------------------------------
// Compose has no Apple system palette, so — exactly like the web/CSS target — reference tokens
// resolve to the light/dark hex approximation and switch at runtime via `isSystemInDarkTheme()`.
// value tokens are literals in both schemes. Structure mirrors DesignTokens: RemSpacing / RemRadius
// (Dp), RemTypography (TextStyle), RemOpacity, and a RemColorScheme (light+dark) provided through a
// RemTheme composable + CompositionLocal, so component TokenSets read `RemColors.current`.
const HEADER_KT = `// GENERATED by tools/generate-tokens.mjs from tokens.json. DO NOT EDIT BY HAND.\n// Run the generator and commit. Compose form of the same token contract as DesignTokens.swift.\n`;
function ktColor(webval) {
  const s = String(webval).trim();
  let r, g, b, a = 255;
  if (s.startsWith("#")) {
    const h = s.slice(1);
    [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
    if (h.length >= 8) a = parseInt(h.slice(6, 8), 16);
  } else if (s.startsWith("rgb")) {
    const m = s.match(/rgba?\(([^)]+)\)/)[1].split(",").map((x) => x.trim());
    r = +m[0]; g = +m[1]; b = +m[2];
    a = m[3] !== undefined ? Math.round(parseFloat(m[3]) * 255) : 255;
  } else { return "Color.Unspecified"; }
  const hx = (n) => n.toString(16).padStart(2, "0").toUpperCase();
  return `Color(0x${hx(a)}${hx(r)}${hx(g)}${hx(b)})`;
}
// The colors in scheme order — same set + names as buildSwift/buildCSS.
function ktColorEntries(light) {
  const c = T.color, rows = [];
  const push = (name, tok) => { const w = webVal(tok); rows.push([name, ktColor(light ? w.light : (w.dark ?? w.light))]); };
  push("backgroundPrimary", c.background.primary);
  push("backgroundSecondary", c.background.secondary);
  push("backgroundTertiary", c.background.tertiary);
  push("labelPrimary", c.label.primary);
  push("labelSecondary", c.label.secondary);
  push("labelTertiary", c.label.tertiary);
  push("separator", c.separator);
  push("fillTertiary", c.fill.tertiary);
  push("buttonBackground", c.buttonBackground);
  push("pillBackground", c.pillBackground);
  for (const [k, v] of Object.entries(c.system)) { if (!k.startsWith("$")) push(`system${k[0].toUpperCase()}${k.slice(1)}`, v); }
  rows.push(["brandBlue", ktColor(c.brand.blue.value)]);
  rows.push(["brandBlueOnFill", ktColor(light ? c.brand.blueOnFill.light : c.brand.blueOnFill.dark)]);
  return rows;
}
const ktWeight = (w) => (w === 700 ? "FontWeight.Bold" : "FontWeight.Normal");
function buildKotlin() {
  const fields = ktColorEntries(true).map(([n]) => `    val ${n}: Color`).join(",\n");
  const scheme = (light) => ktColorEntries(light).map(([n, v]) => `    ${n} = ${v}`).join(",\n");
  const spacing = Object.entries(T.spacing).filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `    val ${k}: Dp = ${v}.dp`).join("\n");
  const radius = Object.entries(T.radius).filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `    val ${k}: Dp = ${v}.dp`).join("\n");
  const roles = T.typography.roles;
  const typo = Object.entries(roles).map(([k, r]) => {
    const mono = r.family === "mono" ? ", fontFamily = FontFamily.Monospace" : "";
    const ls = r.letterSpacing ? `, letterSpacing = ${r.letterSpacing}.sp` : "";
    return `    val ${k} = TextStyle(fontSize = ${r.size}.sp, fontWeight = ${ktWeight(r.weight)}${mono}${ls})`;
  }).join("\n");
  const aliases = Object.entries(T.typography.roleAliases).filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `    val ${k} = ${v}`).join("\n");
  return `${HEADER_KT}@file:Suppress("MagicNumber", "unused")

package com.rem.designsystem.tokens

import androidx.compose.material3.Typography
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** Reference + value colors resolved per scheme (Compose has no Apple system palette). */
data class RemColorScheme(
${fields}
)

val RemLightColors = RemColorScheme(
${scheme(true)}
)

val RemDarkColors = RemColorScheme(
${scheme(false)}
)

val LocalRemColors = staticCompositionLocalOf { RemLightColors }

/** Wrap the app (or a preview) so component TokenSets can read RemColors.current. */
@Composable
fun RemTheme(darkTheme: Boolean = isSystemInDarkTheme(), content: @Composable () -> Unit) {
    CompositionLocalProvider(LocalRemColors provides (if (darkTheme) RemDarkColors else RemLightColors), content = content)
}

object RemColors {
    val current: RemColorScheme
        @Composable get() = LocalRemColors.current
}

object RemSpacing {
${spacing}
}

object RemRadius {
${radius}
}

object RemOpacity {
    const val deemphasized: Float = ${T.opacity.deemphasized.value}f
}

object RemTypography {
${typo}
    val title3Tracking = ${roles.title3.letterSpacing}.sp
${aliases}
}
`;
}

// ---- main -------------------------------------------------------------------
const swift = buildSwift();
const css = buildCSS();
const kt = buildKotlin();
const check = process.argv.includes("--check");

if (check) {
  let stale = false;
  for (const [path, want] of [[OUT_SWIFT, swift], [OUT_CSS, css], [OUT_KT, kt]]) {
    let have = "";
    try { have = readFileSync(path, "utf8"); } catch { /* missing */ }
    if (have !== want) { console.error(`DRIFT: ${path} is out of sync with tokens.json`); stale = true; }
  }
  if (stale) { console.error("Run: node tools/generate-tokens.mjs"); process.exit(1); }
  console.log("tokens: generated files are in sync ✓");
} else {
  writeFileSync(OUT_SWIFT, swift);
  writeFileSync(OUT_CSS, css);
  writeFileSync(OUT_KT, kt);
  console.log(`wrote ${OUT_SWIFT}\nwrote ${OUT_CSS}\nwrote ${OUT_KT}`);
}
