"""Build the canonical paired delivery using trusted publisher-side code."""
import argparse
import fnmatch
import json
from pathlib import Path
import re


def prepare(root: Path, head: str, conclusion: str, changed: list[str], contracts: dict) -> tuple[str, str, list[Path]]:
    if not re.fullmatch(r"[0-9a-f]{40}", head):
        raise ValueError("Full head SHA required")
    pairs: dict[str, dict[str, Path]] = {}
    for platform in ("swiftui", "compose"):
        for path in sorted((root / platform).glob("*.png")):
            key = re.sub(r"^com\.rem\.designsystem_EvidenceSnapshots_[^_]+_", "", path.stem).lower()
            if not re.fullmatch(r"[a-z0-9-]+", key):
                raise ValueError(f"Invalid evidence name: {path.name}")
            pair = pairs.setdefault(key, {})
            if platform in pair:
                raise ValueError(f"Duplicate evidence for {platform} {key}")
            pair[platform] = path.resolve()
    if not pairs:
        raise ValueError("No rendered evidence")
    required = set()
    for contract in contracts.values():
        if any(fnmatch.fnmatchcase(path, pattern) for path in changed for pattern in contract["paths"]):
            required.update(contract["states"])
    missing = [f"{key} / {platform}" for key in sorted(required)
               for platform in ("swiftui", "compose") if platform not in pairs.get(key, {})]
    status = "ready" if conclusion == "success" and not missing else "failed"
    lines = [f"Current head: `{head}`", "",
             "Paired runner-produced evidence: iOS Simulator (SwiftUI) | Android Paparazzi (Compose).",
             "Rendering and coverage checks do not establish visual parity; Reviewer must compare the pixels against the approved contracts.", ""]
    if missing:
        lines += ["**Required evidence missing — delivery blocked:**", "", *[f"- {item}" for item in missing], ""]
    if conclusion != "success":
        lines += ["**Render workflow did not pass.** Builder must repair its failing checks.", ""]
    lines += ["| Screen / component · state | iOS · SwiftUI | Android · Compose |", "|---|:---:|:---:|"]
    attachments = []
    # Required screen states come first, followed by regression/component evidence.
    for key in sorted(pairs, key=lambda key: (key not in required, key)):
        cells = []
        for platform in ("swiftui", "compose"):
            path = pairs[key].get(platform)
            if path:
                cells.append(f"![{platform} {key}]({path})")
                attachments.append(path)
            else:
                cells.append("**Not rendered**")
        lines.append(f"| `{key}` | {' | '.join(cells)} |")
    lines += ["", "Rows marked **Not rendered** are not evidence of cross-platform parity.",
              "", "_Generated by Agent Factory. Delivery workflow authored by Codex._"]
    return status, "\n".join(lines) + "\n", attachments


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence-root", type=Path, required=True)
    parser.add_argument("--head", required=True)
    parser.add_argument("--conclusion", required=True)
    parser.add_argument("--changed-paths", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    contracts = json.loads(Path(__file__).with_name("contracts.json").read_text())
    status, body, attachments = prepare(args.evidence_root, args.head, args.conclusion,
                                        args.changed_paths.read_text().splitlines(), contracts)
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "body.md").write_text(body)
    (args.output / "status").write_text(status)
    (args.output / "attachments.json").write_text(json.dumps([str(p) for p in attachments]))


if __name__ == "__main__":
    main()
